# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_app', '0004_auto_20170726_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(related_name='items', to='wish_list_app.User'),
        ),
    ]
